### DISCUSSION TITLE
Possible to specify which entities to monitor?

### DISCUSSION THREAD

**Discussion by suneworld** [jazzyisj/unavailable-entities-sensor#36] [Q&A] [answered]
Hi!
Instead of the exclusion group, would it be possible to have an inclusion group?

**Comment by jazzyisj** [comment, marked as answer]
You want a sensor that ONLY monitors entities in a group?

```
template:
  - sensor:
      - name: "Unavailable Entities"
        unique_id: unavailable_entities
        icon: "{{ iif(states(this.entity_id)|int(-1) > 0,'mdi:alert-circle','mdi:check-circle') }}"
        state_class: measurement
        unit_of_measurement: entities
        state: >
          {% set entities = state_attr(this.entity_id,'entity_id') %}
          {{ entities|count if entities != none else none }}
        attributes:
          entity_id: >
            {% set ignore_seconds = 60 %}
            {% set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
            {% set entities = expand('group.monitored_entities')|rejectattr('last_changed','ge',ignore_ts) %}
            {{ entities|map(attribute='entity_id')|reject('has_value')|list|sort }}

group:
  monitored_entities:
    entities:
      - sensor.test1
      - sensor.test2
      - sensor.test3
```
