### ISSUE TITLE
Group ignored_unavailable_entities not filtered

### ISSUE THREAD

**Issue by dmtalon** [jazzyisj/unavailable-entities-sensor#24]
Hi,

Pretty new to HA, and was looking for a way to monitor/see unavailable sensors and ran across this.  I enabled packages, and installed w/o any issues, and the sensor is reporting unavailable entities correctly.

The only issue I seem to be having is that having uncommented the 'OPTIONAL' section for ignored_unavailable_entities and adding them, they are not being filtered.

My code looks as follows.

```
group:
  ignored_unavailable_entities:
    entities:
      - binary_sensor.mailbox_battery_is_disconnected
      - binary_sensor.mailbox_battery_temperature_is_low
      - binary_sensor.mailbox_fluid_is_low
      - binary_sensor.mailbox_overheating
      - binary_sensor.mailbox_rechargeable
      - binary_sensor.mailbox_used_as_backup
      - person.home_tablet
      - person.mqtt_user
```

One other thing I changed (which seems to be working) is modify the rejectattr line as described in the readme to include the button group which did work to remove the reporting of a handful of buttons.

`{% set entities = states|rejectattr('domain','in',['group','button'])`
