### ISSUE TITLE
New button entites handle incorrectly 

### ISSUE THREAD

**Issue by ThomDietrich** [jazzyisj/unavailable-entities-sensor#4]
Hey,
a new button entity (e.g. created through https://www.home-assistant.io/integrations/button.mqtt/) has the state Unknown when available. It is currently discovered as a problematic entity by your script. Could you please look into this? Thanks!

![grafik](https://user-images.githubusercontent.com/2870104/150099594-0b93f85e-5b90-4128-9fac-bb4e1cee55d6.png)

**Comment by jazzyisj** [comment]
This exact situation (button entity) is covered in the README.  Maybe I should just add the button domain in to the ignored groups as the default as I imagine this is going to keep coming up and I really don't see a situation where anybody would want to actively monitor buttons for an unknown state.  Honestly I'm not even sure they can have a state of unknown after they have acquired their initial state,  I haven't played with them yet.

You can ignore the button domain entirely.  

Change this line.

`|rejectattr('domain','eq','group')`

To this.

`|rejectattr('domain','in',['group','button'])`

Let me know if this resolves your issue!

**Comment by ThomDietrich** [comment]
Hey Jazzy, I did that as a workaround. However completely ignoring them is not the best solution because Yes unknown shouldn't raise a warning but unavailable should!?

**Comment by jazzyisj** [comment]
The button entity is stateless, as in, it cannot have a state like the on or off state that, for example, a normal switch entity has.

https://www.home-assistant.io/integrations/button/

So as I understand it, the state will _always_ be unknown.  I'm thinking that for most people, simply ignoring the entire domain will suffice.  I'm struggling to come up with a use case where a button would even have an unavailable state, other than if the integration that instantiated them does not load at all in which case it won't be the button entities that would be of concern.

Certainly if you wish to monitor your button entities for that possibility, your modification will work.  Though I would make the following change so you are not iterating the entire states object twice. 
```
                +
                states.button
                |rejectattr('entity_id','in',state_attr('group.ignored_unavailable_entities','entity_id'))
                |rejectattr('last_changed','ge',ignore_ts)
                |selectattr('state','in',['unavailable','none'])
                |map(attribute='entity_id') | list
```

**Comment by ThomDietrich** [comment]
>  I'm struggling to come up with a use case where a button would even have an unavailable state

The button entity is not special in that way. It can be unavailable and it can be the only entity exposed by a device. Hence it would indeed be wise to cover this within your sensor.

```yaml
button:
  - platform: mqtt
    name: test_unavailable_button
    command_topic: "coffee-machine/brew"
    payload_press: "true"
    availability_topic: "coffee-machine/available"
    payload_available: "online"
    payload_not_available: "offline"

```

![grafik](https://user-images.githubusercontent.com/2870104/150318937-d9a3442c-d301-404d-8cb6-d97e7a948fed.png)

**Comment by jazzyisj** [comment]
Huh.  Well thanks for pointing that out.  Sounds like you're good to go for now but I'm going to leave this open a bit and have a real good look at it when I get a chance to see if I can come up with a better way to deal with it.

**Comment by ThomDietrich** [comment]
Sounds fair.

Maybe one thought to add another perspective: The sensor defined is called "unavailable entities", even though entities with the unknown state are listed as well. I might extend your file to generate two sensors, one for "unavailable entities", one for "unknown entities". Within that change I would ignore button for the latter but no special handling is needed for "unavailable entities".

**Comment by jazzyisj** [comment]
You make absolutely valid points and customizing the template, [creating additional template sensors](https://github.com/jazzyisj/unavailable-entities-sensor#multiple-sensors) and monitoring different states is demonstrated in the README and [examples](https://github.com/jazzyisj/unavailable-entities-sensor/blob/main/examples/example_customized_sensor_package.yaml).  

With the idiosyncrasies of the new button entity you have pointed out I think I'm going to add some additional documentation and examples for the situation you have outlined here.

For the default sensor itself though, my goal is to keep it as simple and generic as possible in a way that meets the requirements for the majority of people who need it.  At the end of the day it's really just a simple template sensor.  It just happens to be one that a lot of people starting out with HA want/need and don't know how to create themselves yet.  They can drop this package in and get immediate results.  Once they've got that there are a lot of hints in the README to refine it a bit so it can meet most people's immediate needs.

I had a look at your git profile here.  Something tells me after looking at a few template sensors and the documentation you'll be writing your own templates that will make this one look silly.

I have all kinds of [template sensors in my config](https://github.com/jazzyisj/home-assistant-config/tree/master/templates).  A few of them are just variations of this sensor, others more complicated.  I'm sure you could use some of these for ideas and starting points to create sensors to meet your needs.  As for jinja itself, the [home assistant templating documentation](https://www.home-assistant.io/docs/configuration/templating/) covers a lot of what you need in and the [jinja documentation](https://jinja.palletsprojects.com/en/2.11.x/templates/) is also a great reference.

As for your situation here, if you're like me if you don't get your morning coffee on time it's going to be a bad day.  Since it looks like you're already going to go down the road of creating additional sensors you can take it to the next level and create a separate template binary sensor that monitors just the state of your button entity that you can then utilize in both the UI and for an alert entity.
```
template:
  - binary_sensor:
      - name: 'Coffee Maker Connected'
        unique_id: coffee_maker_connected
        icon: "{{ 'mdi:coffee' if is_state('binary_sensor.coffee_maker_connected','on') else 'mdi:coffee-off' }}"
        device_class: connectivity
        state: "{{ states('button.coffee_machine')|lower not in ['unavailable','none'] }}"

alert:
  coffee_offline:
    name: 'Coffee Offline'
    title: 'Coffee Machine Alert'
    message: 'The coffee maker is offline. Go fix it!'
    entity_id: binary_sensor.coffee_maker_connected
    state: 'off'
    repeat:
      - 5
      - 60
    skip_first: true
    notifiers: thom
    data:
      tag: coffee_offline
```
Just a thought.
