### ISSUE TITLE
Notify only if there is something to notify

### ISSUE THREAD

**Issue by swa72** [jazzyisj/unavailable-entities-sensor#50]
Hi,

I get notifications with an empty message (which is kinda annoying).  I use the version from `detailed_persistent_notification.yaml` with  another condition.

Can someone please give me a hint (and also fix both the notification in `package_unavailable_entities.yaml` and `detailed_persistent_notification.yaml`?

```yaml
   mode: restart
    trigger:
      - platform: state
        entity_id: sensor.unavailable_entities
        attribute: entity_id
        to: ~
    condition:
      - condition: template
        alias: "Sensor state is a valid numerical value"
        value_template: >
          {{ is_number(trigger.from_state.state)
              and is_number(trigger.to_state.state) }}
    action:
      - if:
          - condition: numeric_state
            entity_id: sensor.unavailable_entities
            below: 1
        then:
          - service: persistent_notification.dismiss
            data:
              notification_id: unavailable_entities
        else:
          - service: persistent_notification.create
            data:
              notification_id: unavailable_entities
              title: "Unavailable Entities"
              [...]
```

The trace info reads

```
Executed: 24 April 2024 at 17:04:49
Result:
params:
  domain: persistent_notification
  service: create
  service_data:
    notification_id: unavailable_entities
    title: Unavailable Entities
    message: ''
  target: {}
running_script: false
```

**Comment by jazzyisj** [comment]
Can you send the entire trigger trace?  It will look like this.

```
this:
  entity_id: automation.unavailable_entities_notification
  state: 'on'
  attributes:
    id: unavailable_entities_notification
    last_triggered: '2024-04-24T17:25:54.490727+00:00'
    mode: restart
    current: 0
    friendly_name: Unavailable Entities Notification
  last_changed: '2024-04-24T17:25:28.919957+00:00'
  last_reported: '2024-04-24T17:25:54.515649+00:00'
  last_updated: '2024-04-24T17:25:54.515649+00:00'
  context:
    id: 01HW8J8YNT349EDDCT78S4070P
    parent_id: 01HW8J8YNTY8TS4TG7KSKB1X58
    user_id: null
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: state
  entity_id: sensor.unavailable_entities
  from_state:
    entity_id: sensor.unavailable_entities
    state: '103'
    attributes:
      state_class: measurement
      entity_id:
        - binary_sensor.front_door_lock_intrusion
        - binary_sensor.front_door_lock_keypad_temporary_disabled
        - binary_sensor.garage_door_lock_intrusion
        - binary_sensor.garage_door_lock_keypad_temporary_disabled
        - binary_sensor.garage_door_lock_lock_jammed
        - binary_sensor.garage_door_lock_system_hardware_failure
        - binary_sensor.side_entrance_motion
      unit_of_measurement: entities
      icon: mdi:alert-circle
      friendly_name: Unavailable Entities
    last_changed: '2024-04-24T17:01:27.591182+00:00'
    last_reported: '2024-04-24T17:01:27.591182+00:00'
    last_updated: '2024-04-24T17:01:27.591182+00:00'
    context:
      id: 01HW8GW5A860PVT9VA7YJHSQBD
      parent_id: 01HW8GT8Q8E4A3XPRS3PDCZMDZ
      user_id: null
  to_state:
    entity_id: sensor.unavailable_entities
    state: '103'
    attributes:
      state_class: measurement
      entity_id:
        - alarm_control_panel.garage
        - binary_sensor.front_door_lock_intrusion
        - binary_sensor.front_door_lock_keypad_temporary_disabled
        - binary_sensor.garage_door_lock_intrusion
      unit_of_measurement: entities
      icon: mdi:alert-circle
      friendly_name: Unavailable Entities
    last_changed: '2024-04-24T17:01:27.591182+00:00'
    last_reported: '2024-04-24T17:27:58.560954+00:00'
    last_updated: '2024-04-24T17:27:58.560954+00:00'
    context:
      id: 01HW8JCQQ5XF8H07FH8HKCBDKB
      parent_id: null
      user_id: null
  for: null
  attribute: entity_id
  description: state of sensor.unavailable_entities
```

**Comment by swa72** [comment]
Yep, here we go ...

It appears that sometime between evaluating to 5 and creating the message text, the entities "re-"appear?

```
this:
  entity_id: automation.unavailable_entities_notification
  state: 'on'
  attributes:
    id: unavailable_entities_notification
    last_triggered: '2024-04-24T15:01:10.665700+00:00'
    mode: restart
    current: 0
    friendly_name: Unavailable Entities Notification
  last_changed: '2024-04-24T04:36:12.566163+00:00'
  last_reported: '2024-04-24T15:01:10.667428+00:00'
  last_updated: '2024-04-24T15:01:10.667428+00:00'
  context:
    id: 01HW89ZYC8RTY4KDZK66CXV8HX
    parent_id: 01HW89ZY15E4KA4YD35P3X4X09
    user_id: null
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: state
  entity_id: sensor.unavailable_entities
  from_state:
    entity_id: sensor.unavailable_entities
    state: '5'
    attributes:
      state_class: measurement
      entity_id:
        - sensor.regenradar
        - sensor.rrrainin120min
        - sensor.rrrainin30min
        - sensor.rrrainin60min
        - sensor.rrraintext
      unit_of_measurement: entities
      icon: mdi:alert-circle
      friendly_name: Unavailable Entities
    last_changed: '2024-04-24T15:01:11.009489+00:00'
    last_reported: '2024-04-24T15:01:11.704092+00:00'
    last_updated: '2024-04-24T15:01:11.704092+00:00'
    context:
      id: 01HW89ZY15E4KA4YD35P3X4X09
      parent_id: null
      user_id: null
  to_state:
    entity_id: sensor.unavailable_entities
    state: '5'
    attributes:
      state_class: measurement
      entity_id: []
      unit_of_measurement: entities
      icon: mdi:alert-circle
      friendly_name: Unavailable Entities
    last_changed: '2024-04-24T15:01:11.009489+00:00'
    last_reported: '2024-04-24T15:04:49.974532+00:00'
    last_updated: '2024-04-24T15:04:49.974532+00:00'
    context:
      id: 01HW8A6M744J45HDB6MGJ2FN9T
      parent_id: null
      user_id: null
  for: null
  attribute: entity_id
  description: state of sensor.unavailable_entities
```
