### ISSUE TITLE
Discord Notification

### ISSUE THREAD

**Issue by jpslv** [jazzyisj/unavailable-entities-sensor#64]
Persistent notifications are working, but Discord notifications aren't. Can somebody help me?

```
action: persistent_notification.create
data:
  notification_id: unavailable_entities
  title: Unavailable Entities
  message: |-
    {{ state_attr('group.unavailable_entities', 'entity_id') | join('
    ') }}     
```

```
action: notify.sapiens
metadata: {}
data:
  target: "1318257468836413440"
  message: |-
    {{ state_attr('group.unavailable_entities', 'entity_id') | join('
    ') }}   
```
